[vlive]
title = "Red Velvet ─ Star Board"
url = "https://vlive.tv/channel/DCF447/board/4540?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
contentSelector = ".upload_time--wtBj9"
waitUntil = "networkidle"

[vlive_post]
title = "Red Velvet ─ Notice"
url = "https://vlive.tv/channel/DCF447/board/1112"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = ".writer--pwvK2"
waitUntil = "networkidle"

[smtown_news]
title = "SMTOWN ─ Red Velvet"
url = "https://www.smtown.com/search?type=sub_news&keyword=%EB%A0%88%EB%93%9C%EB%B2%A8%EB%B2%B3"
entrySelector = "ul.search_news.artist li"
titleSelector = "span.title"
linkSelector = "a.btn_text"
imageSelector = "a[class='btn_img bg_cover']"
contentSelector = "span.text"
waitUntil = "networkidle"
